# ECommerce Sales Analysis

-- Create the database
CREATE DATABASE ecommerce;

-- Use the database
USE ecommerce;

-- Create the categories table
CREATE TABLE Categories (
    category_id INT PRIMARY KEY AUTO_INCREMENT,
    category_name VARCHAR(255)
);

-- Create the products table
CREATE TABLE Products (
    product_id INT PRIMARY KEY AUTO_INCREMENT,
    product_name VARCHAR(255),
    description TEXT,
    price DECIMAL(10, 2),
    stock_quantity INT,
    category_id INT,
    FOREIGN KEY (category_id) REFERENCES Categories(category_id)
);

-- Create the customers table
CREATE TABLE Customers (
    customer_id INT PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    email VARCHAR(255),
    phone VARCHAR(20),
    address VARCHAR(255)
);

-- Create the orders table
CREATE TABLE Orders (
    order_id INT PRIMARY KEY AUTO_INCREMENT,
    customer_id INT,
    order_date DATE,
    total_amount DECIMAL(10, 2),
    status ENUM('pending', 'processing', 'shipped', 'delivered') DEFAULT 'pending',
    FOREIGN KEY (customer_id) REFERENCES Customers(customer_id)
);

-- Create the order_items table
CREATE TABLE Order_Items (
    order_item_id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    product_id INT,
    quantity INT,
    price DECIMAL(10, 2),
    FOREIGN KEY (order_id) REFERENCES Orders(order_id),
    FOREIGN KEY (product_id) REFERENCES Products(product_id)
);

-- Create the shipping_details table
CREATE TABLE Shipping_Details (
    shipping_id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    address VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    zipcode VARCHAR(20),
    country VARCHAR(100),
    FOREIGN KEY (order_id) REFERENCES Orders(order_id)
);

/*
## Data Analysis & Findings : 


### Task 1: Write a SQL query to find the total number of orders placed by each customer
Objective: Find the total number of orders placed by each customer.


### Task 2: Write a SQL query to retrieve all orders placed in the year 2024
Objective: Retrieve all orders placed in the year 2024.


### Task 3: Write a SQL query to calculate the total revenue generated by each product
Objective: Calculate the total revenue generated by each product.


### Task 4: Write a SQL query to calculate the monthly total sales for the business
Objective: Calculate the monthly total sales for the business.


### Task 5: Write a SQL query to find how many products are available in each category
Objective: Find the total number of products available in each category.


### Task 6: Write a SQL query to find all customers whose order status is shipped
Objective: Retrieve all customers whose orders have been shipped.


### Task 7: Write a SQL query to identify which cities generate the highest revenue
**Objective:**  
Identify the cities that generate the highest revenue.


### Task 8: Write a SQL query to identify the top 5 customers who have paid the highest total amount
Objective: Identify the top 5 customers based on total purchase amount.


### Task 9: Write a SQL query to find the top 3 product categories with the highest total sales
Objective: Find the top 3 categories with the highest total sales.


### Task 10: Write a SQL query to find the total number of customers who purchased products from each category
Objective: Calculate the total number of customers who purchased products from each category.

*/
