Select * from categories;
SELECT * FROM PRODUCTS;
Select *from customers;
Select * from Orders;
Select * from Order_items;
Select * from Shipping_Details;


# Project Tasks :

-- Q.1 Write a SQL query to find the total number of orders placed by each customer
SELECT o.customer_id,concat(first_name,' ',last_name) as full_name,COUNT(order_id) AS total_orders
FROM orders as o
join customers as c
on o.customer_id=c.customer_id
GROUP BY customer_id;


-- Q.2. Write a SQL query to retrieve all orders placed in 2024 ?
select *
from orders
where year(order_date)=2024;


-- Q.3 Write a SQL query to calculat the total revenue generated by each product?
select p.product_name,sum(oi.quantity*oi.price) as total_sales
from products as p
join order_items as oi
on p.product_id=oi.product_id
group by p.product_name;


-- Q.4 Write a SQL query to calculate the monthly total sales for the business ?
SELECT YEAR(o.order_date) AS year,MONTH(o.order_date) AS month,SUM(oi.quantity * oi.price) AS total_sales
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY YEAR(o.order_date), MONTH(o.order_date)
ORDER BY year, month;


-- Q.5 How many products are there in each category?
select category_name, count(*) as total_products
from products
join categories
on products.category_id = categories.category_id
group by category_name;


-- Q.6 Find the orders of all customers whose order status is shipped.
select *
from customers
join orders
using (customer_id)
where status = "Shipped";


-- Q.7 Find which cities generate the highest revenue?
SELECT sd.city,SUM(o.total_amount) AS total_revenue
FROM orders o
JOIN shipping_details sd 
ON o.order_id = sd.order_id
GROUP BY sd.city
ORDER BY total_revenue DESC;


-- Q.8 Identify the top 5 customers who have paid the highest total amount?
select c.customer_id,concat(first_name,'  ',last_name) as full_name, sum(total_amount) as total_amt
from customers as c
join orders as o
on c.customer_id = o.customer_id
join order_items as od
on o.order_id = od.order_id
group by o.customer_id
order by total_amt desc
limit 5;


-- Q.9 Show top 3 category with the highest total sales generated.
select category_name,sum(oi.quantity*oi.price) as Total_sales
from categories as c
join products as p
on c.category_id=p.category_id
join order_items as oi
on p.product_id=oi.product_id
group by category_name
order by Total_sales desc
limit 3;


-- Q.10 Write a SQL query to find the total number of customers who purchased items from each category:
SELECT c.category_name,COUNT(distinct o.customer_id) AS total_customers
FROM orders o
JOIN order_items oi 
ON o.order_id = oi.order_id
JOIN products p 
ON oi.product_id = p.product_id
JOIN categories c 
ON p.category_id = c.category_id
GROUP BY c.category_name;

